<a href="https://colab.research.google.com/github/Katherin234/Inteligencia-artificial/blob/main/clase1dejulio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#arreglos en 1 dimension se llaman vectores
import numpy as algebraLineal

a=algebraLineal.array([11,22,33])
print(a.shape)
print(type (a))
print(a)

print(a[1])
print(a[:2])
print(a[1:])

a[1] = 888
print(a)


(3,)
<class 'numpy.ndarray'>
[11 22 33]
22
[11 22]
[22 33]
[ 11 888  33]


In [ ]:
b=algebraLineal.array([[1,2,3],[11,22,33],[111,222,333]])
print(b.shape)
print(type (b))
print('Matriz 1')
print(b)

print(b[1,1])


aux=b[1:,1:].copy()
print(aux.shape)
print('Matriz 2')
print(aux)

aux[1, 1] = 1000
print('Matriz 1')
print(b)
print('Matriz 2')
print(aux)

(3, 3)
<class 'numpy.ndarray'>
Matriz 1
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
Matriz 2
[[ 22  33]
 [222 333]]
Matriz 1
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
Matriz 2
[[  22   33]
 [ 222 1000]]


In [ ]:
c=algebraLineal.zeros((4,4))
print(c)
print(c.shape)
d=algebraLineal.full((4,4),9)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [ ]:
e=algebraLineal.eye(3,3)
print(e)
f=algebraLineal.ones((4,5))
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
g=algebraLineal.random.random((5,5))
print(g)

[[1.65588008e-01 3.60811330e-01 9.69311256e-01 2.43776067e-01
  6.73310038e-01]
 [4.08007757e-01 7.08031468e-01 2.00398004e-04 9.86740134e-01
  8.19939689e-01]
 [6.75809238e-01 3.10246334e-01 7.34903063e-01 5.12881293e-01
  3.62082227e-01]
 [8.05413301e-01 1.21448598e-01 1.66352013e-02 7.08208398e-01
  2.67830753e-01]
 [5.45547270e-02 8.30263702e-01 2.40588092e-01 4.49114537e-01
  6.04318533e-01]]


In [ ]:
t=algebraLineal.random.randint(1,20,(4,4))
print(t)
filas=algrebraLineal.array([0,1,2,3])
columnas=algrebraLineal.arange(4)
print(filas)
print(columnas)

t[filas, columnas] = 100


print(t)

[[ 1 16 12 17]
 [14 19  5 11]
 [12 12 10 10]
 [19  8 18  4]]
[0 1 2 3]
[0 1 2 3]
[[100  16  12  17]
 [ 14 100   5  11]
 [ 12  12 100  10]
 [ 19   8  18 100]]


In [ ]:
t=algebraLineal.random.randint(20,51,(6,6))
print(t)

[[48 50 23 33 30 38]
 [43 38 35 48 49 22]
 [23 30 38 35 34 20]
 [41 23 22 38 44 45]
 [33 29 39 35 20 27]
 [34 29 36 47 50 26]]


In [ ]:
filter=(t>45)
print(filter)


print(t[filter])


[[ True  True False False False False]
 [False False False  True  True False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True  True False]]
[48 50 48 49 47 50]


In [ ]:
t=algebraLineal.random.randint(1,101,(10,10))
print(t)


[[29 98 24 25 50 94 42 84 16 95]
 [31 21 79 68 78 48 53 83 45 76]
 [80 41 82 23 99 41 74 27  5  2]
 [98 20 91 77 26 77 24 32 75 78]
 [28 83  4 51 88 33 20  5  6 30]
 [22 37 86 96 88 92 12 35 61 44]
 [94 79  3 79 87 53 26 11 67 15]
 [ 8 94 86 94 43 85 46 56 67 32]
 [39 93 97 49 13 36 66  6 17 85]
 [ 6 14 92 85  4 13 24  3 53 23]]


In [ ]:
filter=(t%2==0)
print(filter)
print(t[filter])

[[False  True  True False  True  True  True  True  True False]
 [False False False  True  True  True False False False  True]
 [ True False  True False False False  True False False  True]
 [ True  True False False  True False  True  True False  True]
 [ True False  True False  True False  True False  True  True]
 [ True False  True  True  True  True  True False False  True]
 [ True False False False False False  True False False False]
 [ True  True  True  True False False  True  True False  True]
 [False False False False False  True  True  True False False]
 [ True  True  True False  True False  True False False False]]
[98 24 50 94 42 84 16 68 78 48 76 80 82 74  2 98 20 26 24 32 78 28  4 88
 20  6 30 22 86 96 88 92 12 44 94 26  8 94 86 94 46 56 32 36 66  6  6 14
 92  4 24]


In [ ]:
t3=algebraLineal.array([1,2,3,4,5],dtype=algebraLineal.float64)
print(t3.dtype)

float64


In [ ]:
x=algebraLineal.array([[1,2],[11,55]])
y=algebraLineal.array([[44,88],[66,45]])
print(x)
print(y)

print(algebraLineal.add(x,y))
print(algebraLineal.subtract(x,y))
print(algebraLineal.multiply(x,y))
print(algebraLineal.divide(x,y))
print(algebraLineal.sqrt(x))


[[ 1  2]
 [11 55]]
[[44 88]
 [66 45]]
[[ 45  90]
 [ 77 100]]
[[-43 -86]
 [-55  10]]
[[  44  176]
 [ 726 2475]]
[[0.02272727 0.02272727]
 [0.16666667 1.22222222]]
[[1.         1.41421356]
 [3.31662479 7.41619849]]


In [ ]:
t=algebraLineal.random.randint(1,10,(2,5))
print(t)
aux=t.mean()
print(aux)
aux=t.mean(axis=0)
print(aux)
aux=t.mean(axis=1)
print(aux)

[[1 9 5 4 1]
 [7 5 6 6 9]]
5.3
[4.  7.  5.5 5.  5. ]
[4.  6.6]


In [ ]:
import numpy as np
a=np.random.randint(1,10,(3,4))
print(a)
#promedio
t=np.mean(a)
print(t)
print(a.mean())

#promedio por filas
t=a.mean(axis=1)
print(t)
#promedio por columnas
t=a.mean(axis=0)
print(t)
#suma de los valores de la matriz
aux=a.sum()
print(aux)
#calcular la mediana
mediana=np.median(a,axis=1)
print(mediana)

[[3 6 4 8]
 [3 8 3 8]
 [1 8 3 4]]
4.916666666666667
4.916666666666667
[5.25 5.5  4.  ]
[2.33333333 7.33333333 3.33333333 6.66666667]
59
[5.  5.5 3.5]


In [ ]:
#Ordenar vectores SORTING
b=np.random.randn(10)
print(b)
print(b.shape)
b.sort()
print(b)

[-0.65563775  0.50609712  0.57221533 -0.31254588  0.70631601  0.34236772
 -0.31177156 -0.32867338 -1.25719292  1.04057677]
(10,)
[-1.25719292 -0.65563775 -0.32867338 -0.31254588 -0.31177156  0.34236772
  0.50609712  0.57221533  0.70631601  1.04057677]


In [ ]:
c=np.array([2,5,1,6,3,5,5,5,4,7,8,9])
print(np.unique(c))
print(c.shape)
c.sort()
print(c)

[1 2 3 4 5 6 7 8 9]
(12,)
[1 2 3 4 5 5 5 5 6 7 8 9]


In [ ]:
palabra1=np.array(['desk','chair','bulb'])
palabra2=np.array(['lamp','bulb','chair'])
t=np.intersect1d(palabra1,palabra2)
print(t)
t2=np.union1d(palabra1,palabra2)
print(t2)
#elementos no presentes en el contenedor 1
t3=np.setdiff1d(palabra1,palabra2)
print(t3)
t4=np.in1d(palabra1,palabra2)
print(t4)
#

['bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']
['desk']
[False  True  True]


In [ ]:
matriz = np.zeros((4, 3))
print(matriz)


replica=np.array([1,2,1])
matriz=matriz+replica
print(matriz)

replicaColumna=np.array([10,10,10])
print(replicaColumna.shape)
replicaColumna=np.reshape(replicaColumna,(3,1))
print(replicaColumna.shape)
matriz = np.zeros((3, 3))
matriz1=replicaColumna+matriz
print(matriz1)

#Matriz de con numeros 45

vector=np.array([45])
matrixZeros=np.zeros((5,5))
print(matrixZeros)

print(matrixZeros+vector)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]]
(3,)
(3, 1)
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]
