<a href="https://colab.research.google.com/github/Katherin234/Inteligencia-artificial/blob/main/Python_%26_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# Importar numpy ver la version
import numpy as np

version = np.__version__
print(version)

1.25.2


In [16]:
#Crear una matriz de una dimension
Matriz1D = np.arange(10)
print(Matriz1D)


[0 1 2 3 4 5 6 7 8 9]


In [17]:
#Cree un vector aleatorio de tamaño 10 y reemplace el valor máximo por 0
vector = np.random.randint(0, 100,(10))
print(vector)
valor_maximo = vector.max()
vector[vector == valor_maximo] = 0
print(vector)

[32 37 46 52 42 27 15 97 30 70]
[32 37 46 52 42 27 15  0 30 70]


In [18]:
#Imprima el número 8 de la siguiente matriz:
matriz = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(matriz[1,2])

8


In [19]:
#Imprima los números [3, 4, 5] de la siguiente matriz:
matriz = np.arange(8)
print(matriz[3:6])

[3 4 5]


In [20]:
# Imprime los últimos 4 números de la siguiente matriz:
matriz = np.arange(8)
print(matriz)

print(matriz[6])

print(matriz[-4:])

[0 1 2 3 4 5 6 7]
6
[4 5 6 7]


In [21]:
#Crea una matriz numérica de 3 × 3 de todos los True
matriz = np.full((3, 3), True, dtype=bool)
print(matriz)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [22]:
#Extrae todos los números pares de arr

arr = np.arange(10)
print(arr)
impares = arr [arr % 2!= 0]
print(impares)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [23]:
#Crea un vector con valores que van desde 10 a 49
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [24]:
import numpy as np

In [25]:
# Invertir un vector (el primer elemento pasa a ser el último
vector = np.arange(10)
vector = vector[::-1]
print(vector)

[9 8 7 6 5 4 3 2 1 0]


In [26]:
# Crea una matriz de 10x10 con valores enteros aleatorios y encuentra los valores mínimo y máximo
matriz = np.random.randint(1, 101, (10, 10))

minimo_valor = np.min(matriz)
maximo_valor = np.max(matriz)

print("Matriz aleatoria de 10x10:")
print(matriz)
print("Valor mínimo en la matriz:", minimo_valor)
print("Valor máximo en la matriz:", maximo_valor)

Matriz aleatoria de 10x10:
[[ 98  32  40  33   4 100  65  86  49  46]
 [ 39  59  65  19  68  84  10  63  84  72]
 [ 24  29   7  53  70  96  60  51  24  68]
 [ 47  75  24  50  86  17  47  83  74  84]
 [  7  19  24  29   8  29  15  96  85  96]
 [ 61   9  93  60  24  58  86  42  25  15]
 [ 18  24  34  45  74  78  74  67  57  14]
 [ 57  92  98   2  67  68  65  67  53  43]
 [ 34  69  18  43  19  96  54  39  99  22]
 [ 33  49  97  91  32  44  23  83  29  31]]
Valor mínimo en la matriz: 2
Valor máximo en la matriz: 100


In [27]:
# Crea una matriz de 3x3x3 con valores aleatorios
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.92229912 0.83738682 0.52180166]
  [0.43830164 0.55383579 0.96439616]
  [0.49992562 0.05049517 0.12541107]]

 [[0.25674144 0.10010068 0.21452702]
  [0.67778516 0.02803813 0.83684381]
  [0.88157876 0.66495005 0.35242634]]

 [[0.05995034 0.32005974 0.31271634]
  [0.23528981 0.11349036 0.94233363]
  [0.15897654 0.79772062 0.21219728]]]


In [28]:
# Reemplazar todos los números impares en arr con -1
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1

print("Arreglo con números impares reemplazados por -1:", arr)

Arreglo con números impares reemplazados por -1: [-1  2 -1  4 -1  6 -1  8 -1]


In [29]:
# Crea una matriz de tipo float
float_array = np.array([1.0, 2.5, 3.7, 4.2, 5.9])
print(float_array)

[1.  2.5 3.7 4.2 5.9]


In [30]:
# Convertir una matriz 1D en una matriz 2D con 2 filas


In [31]:
import numpy as np
matriz1d = np.array([1, 2, 3, 4, 5, 6])
print('Matriz de 1 dimension')
print(matriz1d)
# Convertir a matriz 2D con 2 filas
print('Matriz de 2 dimensiones')
matriz2d = matriz1d.reshape(2, -1)  # -1 infiere el número de columnas

print(matriz2d)

Matriz de 1 dimension
[1 2 3 4 5 6]
Matriz de 2 dimensiones
[[1 2 3]
 [4 5 6]]


In [32]:
# ¿Cómo encontrar valores comunes entre dos matrices?
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)

v_comun = np.intersect1d(Z1, Z2)
print(v_comun)

[1 4 0 0 9 2 7 6 3 7]
[3 2 8 6 2 8 8 9 9 0]
[0 2 3 6 9]


In [33]:
# Considere dos matrices aleatorias A y B, verifique si son iguales
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
son_iguales = np.array_equal(A, B)

print(f"Las matrices son iguales: {son_iguales}")

Las matrices son iguales: False


In [34]:
# Apilar matrices a y b verticalmente
a = np.array([1, 2, 3])
b = np.array([4, 5])

# Apilar matrices horizontalmente y transponer
matriz_apilada = np.hstack((a, b)).T

print(matriz_apilada)

[1 2 3 4 5]


In [35]:
# Apile las matrices ayb horizontalmente.
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
print(a)
print(b)
matriz_apilada = np.vstack((a, b)).T
print('Matriz Apilada')
print(matriz_apilada)

[[1 2]
 [3 4]]
[5 6]
Matriz Apilada
[[1 3 5]
 [2 4 6]]


In [36]:
# Obtener todos los elementos entre 5 y 10 de la matriz tmp.
tmp = np.arange(15)
print(tmp)
elementos_filtrados = tmp[5:11]
print(elementos_filtrados)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10]


In [37]:
#¿Cómo hacer una función de Python que maneje escalares para que funcione en matrices numerosas?
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [38]:
# Vectorizar la función maxx
pair_max = np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

resultado = pair_max(a, b)

print("Array a:", a)
print("Array b:", b)
print("\nResultado:", resultado)


Array a: [5 7 9 8 6 4 5]
Array b: [6 3 4 8 9 7 1]

Resultado: [6 7 9 8 9 7 5]


In [39]:
arr = np.arange(9).reshape(3,3)
print(arr)

# Intercambiar columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("\nColumna 1 y 2 intercambiadas:")
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Columna 1 y 2 intercambiadas:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [40]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]


array_2d = np.random.uniform(5, 10, size=(5, 3))

print(array_2d)

[[8.21416259 6.76757979 8.73174301]
 [9.08209193 9.30406972 5.69664905]
 [6.4228855  6.28527069 6.29610748]
 [6.80740665 8.28974236 9.36190281]
 [8.61749247 9.96754091 5.92484704]]
