<a href="https://colab.research.google.com/github/Katherin234/Inteligencia-artificial/blob/main/Python_%26_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importar numpy ver la version
import numpy as np

version = np.__version__
print(version)

1.25.2


In [ ]:
#Crear una matriz de una dimension
Matriz1D = np.arange(10)
print(Matriz1D)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Cree un vector aleatorio de tamaño 10 y reemplace el valor máximo por 0
vector = np.random.randint(0, 100,(10))
print(vector)
valor_maximo = vector.max()
vector[vector == valor_maximo] = 0
print(vector)

[97 50 51 36  9  0 43 95 72 28]
[ 0 50 51 36  9  0 43 95 72 28]


In [ ]:
#Imprima el número 8 de la siguiente matriz:
matriz = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(matriz[1,2])

8


In [ ]:
#Imprima los números [3, 4, 5] de la siguiente matriz:
matriz = np.arange(8)
print(matriz[3:6])

[3 4 5]


In [ ]:
# Imprime los últimos 4 números de la siguiente matriz:
matriz = np.arange(8)
print(matriz)

print(matriz[6])

print(matriz[-4:])

[0 1 2 3 4 5 6 7]
6
[4 5 6 7]


In [ ]:
#Crea una matriz numérica de 3 × 3 de todos los True
matriz = np.full((3, 3), True, dtype=bool)
print(matriz)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#Extrae todos los números pares de arr

arr = np.arange(10)
print(arr)
impares = arr [arr % 2p!= 0]
print(impares)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [ ]:
#Crea un vector con valores que van desde 10 a 49
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np

In [ ]:
# Invertir un vector (el primer elemento pasa a ser el último
vector = np.arange(10)
vector = vector[::-1]
print(vector)

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# Crea una matriz de 10x10 con valores enteros aleatorios y encuentra los valores mínimo y máximo
matriz = np.random.randint(1, 101, (10, 10))

minimo_valor = np.min(matriz)
maximo_valor = np.max(matriz)

print("Matriz aleatoria de 10x10:")
print(matriz)
print("Valor mínimo en la matriz:", minimo_valor)
print("Valor máximo en la matriz:", maximo_valor)

Matriz aleatoria de 10x10:
[[ 90  58  77  52 100  99  70  94  50  11]
 [ 15  74  77  40  20  42  33  32  88  49]
 [ 53  42  51  41  78  92  93  18  75  71]
 [ 80  12  98  97  45  42  64  67  26  70]
 [ 36  74   6  73  98  61  93   4  46  93]
 [ 70  62  49  93  54  38  62  61  23  57]
 [ 27  67  65  76  41  95  20  84  66  99]
 [ 77  81  78  15  36  55  97  45  33   4]
 [ 63  19  21  62  34  60  46  58  42  93]
 [ 88  40  12  62  54  28  43  75  71  92]]
Valor mínimo en la matriz: 4
Valor máximo en la matriz: 100


In [ ]:
# Crea una matriz de 3x3x3 con valores aleatorios
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.71662977 0.33061578 0.09257749]
  [0.11740599 0.67227313 0.36602531]
  [0.95675114 0.75298519 0.21148805]]

 [[0.3197382  0.03702846 0.71518198]
  [0.88660309 0.17458439 0.80973468]
  [0.24483658 0.48549832 0.56587647]]

 [[0.58670413 0.76233577 0.14290219]
  [0.51727896 0.07089388 0.35019269]
  [0.81468657 0.23263652 0.47713644]]]


In [ ]:
# Reemplazar todos los números impares en arr con -1
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1

print("Arreglo con números impares reemplazados por -1:", arr)

Arreglo con números impares reemplazados por -1: [-1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# Crea una matriz de tipo float
float_array = np.array([1.0, 2.5, 3.7, 4.2, 5.9])
print(float_array)

[1.  2.5 3.7 4.2 5.9]


In [ ]:
# Convertir una matriz 1D en una matriz 2D con 2 filas


In [ ]:
import numpy as np
matriz1d = np.array([1, 2, 3, 4, 5, 6])
print('Matriz de 1 dimension')
print(matriz1d)
# Convertir a matriz 2D con 2 filas
print('Matriz de 2 dimensiones')
matriz2d = matriz1d.reshape(2, -1)  # -1 infiere el número de columnas

print(matriz2d)

Matriz de 1 dimension
[1 2 3 4 5 6]
Matriz de 2 dimensiones
[[1 2 3]
 [4 5 6]]


In [ ]:
# ¿Cómo encontrar valores comunes entre dos matrices?
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)

v_comun = np.intersect1d(Z1, Z2)
print(v_comun)

[3 4 1 9 5 9 8 8 6 9]
[8 4 5 0 0 0 9 7 4 2]
[4 5 8 9]


In [ ]:
# Considere dos matrices aleatorias A y B, verifique si son iguales
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
son_iguales = np.array_equal(A, B)

print(f"Las matrices son iguales: {son_iguales}")

Las matrices son iguales: False


In [ ]:
# Apilar matrices a y b verticalmente
a = np.array([1, 2, 3])
b = np.array([4, 5])

# Apilar matrices horizontalmente y transponer
matriz_apilada = np.hstack((a, b)).T

print(matriz_apilada)

[1 2 3 4 5]


In [ ]:
# Apile las matrices ayb horizontalmente.
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
print(a)
print(b)
matriz_apilada = np.vstack((a, b)).T
print('Matriz Apilada')
print(matriz_apilada)

[[1 2]
 [3 4]]
[5 6]
Matriz Apilada
[[1 3 5]
 [2 4 6]]


In [ ]:
# Obtener todos los elementos entre 5 y 10 de la matriz tmp.
tmp = np.arange(15)
print(tmp)
elementos_filtrados = tmp[5:11]
print("Elementos entre 5 y 10 usando slicing:", elementos_filtrados)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Elementos entre 5 y 10 usando slicing: [ 5  6  7  8  9 10]


In [ ]:
#¿Cómo hacer una función de Python que maneje escalares para que funcione en matrices numerosas?
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5